services:
  auth-service:
    container_name: auth-service_container
    build:
      context: ./auth-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Prague
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - internal
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  core:
    container_name: core_container
    build:
      context: ./core
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
      - AI_SERVICE_URL=${AI_GRADING_SERVICE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - TZ=Europe/Prague
    depends_on:
      auth-service:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    networks:
      - internal
    ports:
      - "8080:8080"
    volumes:
      - question_images:/app/question-images
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ai-grading-service:
    container_name: ai-grading-service_container
    build:
      context: ./ai-grading-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CORE_SERVICE_URL=${CORE_SERVICE_URL}
      - TZ=Europe/Prague
    depends_on:
      core:
        condition: service_healthy
        restart: true
      db:
        condition: service_healthy
        restart: true
    networks:
      - internal
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
      TZ: Europe/Prague
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME} -d ${SPRING_DATASOURCE_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: redis_container
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - internal
    command: redis-server --save 60 1 --loglevel warning
    environment:
      - TZ=Europe/Prague
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  notification-service:
    container_name: notification-service_container
    build:
      context: ./notification-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Prague
    depends_on:
      core:
        condition: service_healthy
        restart: true
    networks:
      - internal
    ports:
      - "8082:8082"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  chat-service:
    container_name: chat-service_container
    build:
      context: ./chat-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Prague
    depends_on:
      core:
        condition: service_healthy
        restart: true
    networks:
      - internal
    ports:
      - "8083:8083"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    environment:
      - TZ=Europe/Prague
    depends_on:
      core:
        condition: service_healthy
        restart: true
    networks:
      - internal
    ports:
      - "5173:9533"

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
  question_images:
  redis_data: